#Server Port
server.port=8082

#Applicaion Name
spring.application.name=dsai_apg_sm_user

#My SQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/irt1
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

#Integrating Variables
user.userType=Industry_User
user.status=Pending_Approval
user.reject=Rejected

#id generator key prefix
user.keyPrefix=user
role.keyPrefix=role
document.keyPrefix=document
factory.keyPrefix=fa
volunteer.keyPrefix=volu

# Dynamic form - Table Id Prefix
question.keyPrefix=ques_
form.keyPrefix=dynamic_form_
ans.keyPrefix=ans_
formUserLink.keyPrefix = form_user_link_
dept.keyPrefix = dept_

#Publisher Subscriber GCP Configurations
spring.cloud.gcp.project-id=dsai-safety-management
spring.cloud.gcp.pubsub.subscriber.executor-threads=4
spring.cloud.gcp.credentials.location=classpath:dsai-safety-management-8bb83aec31b4.json
spring.cloud.gcp.pubsub.enabled=true

spring.security.basic.enabled=false
