spring.application.name=dsai_apg_sm_notification
springdoc.swagger-ui.path=/swagger-ui-custom.html

#Server Port
server.port=8082

#MySql Information
spring.datasource.url=jdbc:mysql://localhost:3306/notification_microservice
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#CORS CONFIGURATIONS#
spring.mvc.cors.allowed-origins=http://localhost:4200
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.mvc.cors.allowed-headers=*
spring.mvc.cors.allow-credentials=true

#TWILIO SMS CONFIGURATION#
twilio.account_sid=AC9d63d0124da757a856d3c0c88fc5e680
twilio.auth_token=ff3bc80ddc364c3e26a3af06ba2359b5
twilio.trial_number=+12184033254

#GMAIL CONFIGURATONS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sriramsphere@gmail.com
spring.mail.password=ewkdpepvmuhrtgvk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Eureka Client properties details
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

#Publisher Subscriber Configurations
spring.cloud.gcp.project-id=dsai-safety-management
spring.cloud.gcp.pubsub.subscriber.executor-threads=4
spring.cloud.gcp.credentials.location=file:/Users/welcome/Hero/Science/Keys/dsai-safety-management-8bb83aec31b4.json
spring.cloud.gcp.pubsub.enabled=true
